# Site settings
title: Enterprise investor
description: 'A blog about investment based on financial analysis'
url: 'http://tradeamateur.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'AmateurTrader'
  email: amateurtrader@gmail.com
  twitter_username: amateurtrader
  facebook_username: amateurtrader
  github_username:  amateurtrader
  linkedin_username:  amateurtrader

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
